import { useQuery } from '@apollo/client'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { PostsDocument, PostsQuery, PostsQueryVariables } from '../generated'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const { data, error, loading } = useQuery<PostsQuery, PostsQueryVariables>(PostsDocument);

  if(loading) return (
    <main className={styles.main}>
        Loading...
    </main>
  );

  if(error) return (
    <main className={styles.main}>
      {error.message}
    </main>
  )

  // If we're here, we have some data in our data variable

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
